# -*- coding: utf-8 -*-
"""Exercicio7Sinais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zNfBhjClpOhoO0B7NmHFNU39Fl7H6ylZ
"""

import numpy as np
import matplotlib.pyplot as plt

def main():
  t = np.linspace(0,5,5)
  Ts = 0.0001

  #Sinal de entrada
  x = []
  for i in range(0,5,1):
    if (i<=1):
      x.append(1)
    else:
      x.append(0)

  #Resposta ao impulso
  h = []
  for i in range(0,5,1):
    if (i<=2):
      h.append(1)
    else:
      h.append(0)

  #Convolução
  y = []
  y = np.convolve(h,x)*Ts

  #Gráficos

  t1 = np.linspace(0,10,9)

  #Sinal de entrada
  plt.figure(figsize=(12, 6))
  plt.plot(t,x,'c-',label = "Função de Entrada")
  plt.xlabel("(t)")
  plt.ylabel("x(t)")
  plt.show()

  #Resposta ao impulso

  plt.figure(figsize=(12, 6))
  plt.plot(t,h,'c-',label = "Resposta ao Impulso")
  plt.xlabel("(t)")
  plt.ylabel("h(t)")
  plt.show()

  #Convolução

  plt.figure(figsize=(12, 6))
  plt.plot(t1,y,'c-',label = "Convolução")
  plt.xlabel("(t1)")
  plt.ylabel("xy(t1)")
  plt.show()

main()

